figure: fig5
modules:
  fig5_cellchat_build:
    obj_gr_rds: data/Fig5/obj_gr_newanno.rds
    obj_oo_rds: data/Fig5/oocyte_edit.rds
    out_dir: results/Fig5/cellchat
    prefix: fig5
    mode: all
    export_comm_tables: true
    gc_sample_col: sample
    gc_celltype_col: celltype
    gc_celltype_levels:
    - Granulosa Progenitor
    - Preantral1
    - Preantral2
    - Mitotic1
    - Mitotic2
    - Antral Mural
    - Atretic
    oo_stage_col: stage
    oocyte_exclude_stages:
    - MII
    gc_exclude_celltypes:
    - Atretic
    group_new_levels:
    - EGO
    - GO1
    - GO2
    - GO3
    - FGO
    - Granulosa Progenitor
    - Preantral1
    - Preantral2
    - Mitotic1
    - Mitotic2
    - Antral Mural
    compute_type: triMean
    population_size: false
    seed_use: 888
    min_cells: 10
    stage_subsets:
    - name: EGO
      keep_labels:
      - EGO
      - Granulosa Progenitor
    - name: GO1
      keep_labels:
      - GO1
      - Preantral1
      - Preantral2
      - Mitotic1
    - name: GO2
      keep_labels:
      - GO2
      - Mitotic1
      - Mitotic2
    - name: GO3
      keep_labels:
      - GO3
      - Mitotic2
      - Antral Mural
    - name: FGO
      keep_labels:
      - FGO
      - Mitotic2
      - Antral Mural
